name: "CodeQL Scan"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # weekly scan on Sunday

jobs:
  analyze:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, html, css  # update based on your stack

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
